### PR TITLE
Swizzling in a dispatch_once

### PR DESCRIPTION
**Pull request by Kemcake**
Swizzling has to be done in a dispatch_once (as seen on [NSHipster](http://nshipster.com/method-swizzling/#dispatch_once) )
This fix select events not triggered when a new interfaceController appears ( #9 )

### CODE REVIEW

**Comment by rnystrom** [comment]
Nice! This is awesome. One note though, if we have multiple `WKInterfaceController` subclasses, then we will only swizzle for the one.

An option that I'd love your thoughts on: What if we moved the swizzling to `+load` and required anyone that wanted to use the custom events to override `load` and call the swizzle method?

**Comment by acoomans** [comment]
+load seems definitely better

**Comment by Kemcake** [comment]
Yep, multiple subclasses don't work. 
I agree for the `+load`, it's way more clean and it seem to work!

**Comment by rnystrom** [comment]
@Kemcake does this implementation work both with subclasses of `WKInterfaceController` as well as the original navigation issue you pointed out? Does the included sample project need to be updated? (e.g. subclasses need to call `+load` right?)

Also, I think we still need to remove the `dispatch_once` as if you have multiple subclasses, this will only work for the one loaded first. Right?

**Comment by Kemcake** [comment]
Yes, this work with subclasses and with navigation, I tested it with 3 subclasses pushing each other. (And actually submitted an app using it ^^)

I've updated the sample project, but you don't need to implement `+load` in your subclass, swizzle will be done by default, but you can override it by implementing the original method `didSelectRowAtIndex`. So you can use default or custom methods.
The `dispatch_once` works as expected, for each new subclass of `WKInterfaceController` swizzling will be called independently. 

PS: You can try multiple subclasses + navigation on this branch if you want : [Kemcake/IGInterfaceDataTable/tree/swizzling-test](https://github.com/Kemcake/IGInterfaceDataTable/tree/swizzling-test)

**Comment by rnystrom** [comment]
@Kemcake just tried your branch out, awesome!! Totally works.

**Pull request merged**
